.PHONY: clean All

All:
	@echo "----------Building project:[ linear-frequency2voltage-sensor - Debug ]----------"
	@cd "/home/i40apps/Industry-4.0/Picominer-2.0/Picominer-Simulators/simulators/linear-frequency2voltage-sensor" && "$(MAKE)" -f  "linear-frequency2voltage-sensor.mk"
clean:
	@echo "----------Cleaning project:[ linear-frequency2voltage-sensor - Debug ]----------"
	@cd "/home/i40apps/Industry-4.0/Picominer-2.0/Picominer-Simulators/simulators/linear-frequency2voltage-sensor" && "$(MAKE)" -f  "linear-frequency2voltage-sensor.mk" clean
